%YAML:1.2
objects:
    cheezit_big_original: 
        files: ['images/cheezit.jpg']
        size: [0.062, 0.16, 0.226]
    genuine_joe_plastic_stir_sticks:
        files: ['images/stirsticks.jpg']
        size: [0.0, 0.0, 0.0]
    crayola_64_ct:
        files: []
        size: [0.0, 0.0, 0.0]
    expo_dry_erase_board_eraser:
        files: ['images/expo.jpg']
        size: [0.0, 0.0, 0.0]
    elmers_washable_no_run_school_glue:
        files: ['images/glue.jpg']
        size: [0.0, 0.0, 0.0]
    kygen_squeakin_eggs_plush_puppies:
        files: []
        size: [0.0, 0.0, 0.0]
shelf:
    A: [.005, .35, -.260, -.005, .734, .962]
    B: [.005, .415, -.563, -.272, .734, .962]
    C: [.005, .415, -.833, -.575, .734, .962]
    D: [.005, .39,   -.260, -.005, .504, .692]
    E: [.005, .415, -.563, -.272, .504, .692]
    F: [.005, .415, -.833, -.575, .504, .692]
    G: [.005, .415, -.260, -.005, .277, .462]
    H: [.005, .415, -.563, -.272, .277, .462]
    I: [.005, .415, -.833, -.575, .277, .462]
    J: [.005, .415, -.260, -.005, .010, .235]
    K: [.005, .415, -.563, -.272, .010, .235]
    L: [.005, .415, -.833, -.575, .010, .235]
