%YAML:1.2
objects:
    cheezit_big_original: 
        files: ['images/cheezit.jpg']
        size: [0.062, 0.16, 0.226]
        colors: ['orange', 'yellow', 'red']
    genuine_joe_plastic_stir_sticks:
        files: ['images/stirsticks.jpg']
        size: [0.095, 0.107, 0.145]
        colors: ['red', 'orange']
    crayola_64_ct:
        files: ['images/crayola.jpg']
        size: [0.037, 0.125, 0.145]
        colors: ['yellow', 'green', 'blue', 'orange']
    expo_dry_erase_board_eraser:
        files: ['images/expo.jpg']
        size: [0.035, 0.055, 0.13]
        colors: ['blue', 'green', 'yellow']
    elmers_washable_no_run_school_glue:
        files: ['images/glue.jpg']
        size: [0.025, 0.06, 0.145]
        colors: ['blue', 'orange', 'red']
    kyjen_squeakin_eggs_plush_puppies:
        files: []
        size: [0.06, 0.121, 0.18]
        colors: ['yellow', 'orange', 'blue', 'red']
    oreo_mega_stuf:
        files: []
        size: [0.06, 0.155, 0.2]
        colors: ['blue']
    champion_copper_plus_spark_plug:
        files: []
        size: [0.02, 0.025, 0.095]
        colors: ['orange', 'red']
    munchkin_white_hot_duck_bath_toy:
        files: []
        size: [0.065, 0.095, 0.13]
        colors: ['yellow', 'blue']
    mommys_helper_outlet_plugs:
        files: []
        size: [0.055, 0.09, 0.19]
        colors: ['white']
    sharpie_accent_tank_style_highlighters:
        files: []
        size: [0.023, 0.116, 0.125]
        colors: ['orange', 'blue', 'green']
    stanley_66_052:
        files: []
        size: [0.02, 0.1, 0.195]
        colors: ['yellow', 'orange']
    safety_works_safety_glasses:
        files: []
        size: [0.05, 0.07, 0.2]
        colors: ['green', 'blue', 'yellow']
    paper_mate_12_count_mirado_black_warrior:
        files: []
        size: [0.016, 0.05, 0.195]
        colors: ['blue']
    mark_twain_huckleberry_finn:
        files: []
        size: [0.012, 0.132, 0.21]
        colors: ['green', 'blue', 'yellow']
    first_years_take_and_toss_straw_cup:
        files: []
        size: [0.08, 0.09, 0.17]
        colors: ['blue', 'yellow', 'orange', 'red']
    feline_greenies_dental_treats:
        files: []
        size: [0.04, 0.175, 0.21]
        colors: ['green', 'yellow', 'orange']
    laugh_out_loud_joke_book:
        files: []
        size: [0.01, 0.108, 0.177]
        colors: ['orange', 'blue', 'red']
    kong_air_dog_squeakair_tennis_ball:
        files: []
        size: [0.07, 0.108, 0.19]
        colors: ['green', 'red', 'blue', 'orange', 'yellow']
    highland_6539_self_stick_notes:
        files: []
        size: [0.05, 0.04, 0.115]
        colors: ['yellow']
    kong_sitting_frog_dog_toy:
        files: []
        size: [0.045, 0.09, 0.21]
        colors: ['green', 'yellow', 'red']
    kong_duck_dog_toy:
        files: []
        size: [0.05, 0.09, 0.18]
        colors: ['yellow', 'orange']
    rolodex_jumbo_pencil_cup:
        files: []
        size: [0.107, 0.14, 0.107]
        colors: ['black', 'blue']
    mead_index_cards:
        files: []
        size: [0.02, 0.076, 0.127]
        colors: ['orange', 'red']
    dr_browns_bottle_brush:
        files: []
        size: [0.05, 0.107, 0.305]
        colors: ['blue', 'green']
    test_object:
        files: []
        size: [0.0, 0.0, 0.0]
        colors: []
shelf:
    A: [-0.43, -.01,  0.17764, 0.39,    1.55794, 1.77212]
    B: [-0.43, -.01, -0.12, 0.14331, 1.55794, 1.77212]
    C: [-0.43, -.01, -0.41,   -0.15764, 1.55794, 1.77212]
    D: [-0.43, -.01,  0.17764, 0.39,    1.32733, 1.50775]
    E: [-0.43, -.01, -0.14331, 0.14331, 1.32733, 1.50775]
    F: [-0.43, -.01, -0.41,   -0.15764, 1.32733, 1.50775]
    G: [-0.43, -.01,  0.15764, 0.41,    1.11053, 1.29092]
    H: [-0.43, -.01, -0.14331, 0.14331, 1.11053, 1.29092]
    I: [-0.43, -.01,  0.41,   -0.15764, 1.11053, 1.29092]
    J: [-0.43, -.01,  0.15764, 0.41,    0.83651, 1.05069]
    K: [-0.43, -.01, -0.14331, 0.14331, 0.83651, 1.05069]
    L: [-0.43, -.01,  0.41,   -0.15764, 0.83651, 1.05069]
