%YAML:1.0
cheezit_big_original: ['images/cheezit.jpg']
genuine_joe_plastic_stir_sticks: ['images/stirsticks.jpg']
crayola_64_ct: []
expo_dry_erase_board_eraser: ['images/expo.jpg']
elmers_washable_no_run_school_glue: ['images/glue.jpg']
kygen_squeakin_eggs_plush_puppies: []
